name: Test self-hosted runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Show machine info
        run: |
          whoami
          hostname
          ip a | head -n 30
